# System-wide .bashrc file for interactive bash(1) shells.
parse_git_branch() {
	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

if [ -z "$PS1" ]; then
   return
fi

PS1="\u@\h \W\$(parse_git_branch) \$ "
# Make bash check its window size after a process completes
shopt -s checkwinsize

PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
